application: eatjapanboston
version: dev-aebadkjsk
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: static/images

- url: /bootstrap
  static_dir: bootstrap-3.3.5-dist

- url: /(.*\.json)$
  static_dir: static

- url: /(|about|favorites)
  script: main.app

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
